# Configuration file for the Sphinx documentation builder.



# -- Project information -----------------------------------------------------

project = 'CanFlood2'
copyright = '2025, NRCan'
author = 'Seth Bryant'

 

# The full version, including alpha/beta/rc tags
release = '2.0.0'
version = '2.0.0'

# -- General configuration

extensions = [
    'sphinx.ext.duration',
    'sphinx.ext.doctest',
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.intersphinx',
    'sphinx.ext.githubpages'
]

intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'sphinx': ('https://www.sphinx-doc.org/en/master/', None),
}
intersphinx_disabled_domains = ['std']

templates_path = ['_templates']

# -- Options for HTML output

html_theme = 'sphinx_rtd_theme'

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = 'assets/logo.jpg'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# locale_dirs = ['locale/']   # path is example but recommended.
# gettext_uuid = True
# gettext_compact = False 


# Enable numref
numfig = True
numfig_secnum_depth = 1
numfig_format = {
    'figure': 'Figure %s',
    'table': 'Table %s',
    'code-block': 'Listing %s'
}


# Enable nitpicky mode to warn about missing references
nitpicky = True

# Optionally, specify a list of references to ignore if necessary
nitpick_ignore = [
    # ('py:class', 'SomeClassName'),
]


